[package]
name = "rust_finder"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust_finder"
path = "src/main.rs"

[dependencies]
scraper = "0.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rayon = "1"